#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain="$1"
subdomain="$2"

# Default subdomains to audit
subdomains=("www" "lb-01" "web-01" "web-02")

if [[ ! -z $subdomain ]]; then
  subdomains=($subdomain)
fi

for sub in "${subdomains[@]}"; do
  dig_output=$(dig +short A "$sub.$domain")
  if [[ -n "$dig_output" ]]; then
    echo "The subdomain $sub is a A record and points to $dig_output"
  else
    echo "The subdomain $sub does not have an A record"
  fi
done