#!/usr/bin/env bash
# Script configures web-01 to block all incoming traffic except
#+ ports 22, 443 and 80

# Check if the script is being run with root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run with root privileges (sudo)."
    exit 1
fi
# Install UFW if not already installed
if ! command -v ufw &>/dev/null; then
    apt update
    apt install ufw -y
fi

sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
# Disable UFW to start with a clean slate
ufw disable
# Reset UFW rules to default settings
ufw reset
# Set the default policies to deny incoming and allow outgoing
ufw default deny incoming
ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
ufw --force enable
# Display the status to verify the rules
ufw status verbose
