#!/usr/bin/env bash
# Script configures web-01 to block all incoming traffic except
#+ ports 22, 443 and 80

sudo apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw enable
sudo ufw default allow outgoing
sudo ufw default allow incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw allow out 443/tcp
sudo ufw allow out 80/tcp
sudo ufw enable

sudo ufw status
